### ISSUE TITLE
Integration still tries to get "last recorded" information even if Last_Record sensor entity is disabled. - again

### ISSUE THREAD

**Issue by skynet01** [JimStar/reolink_cctv#112]
Describe the bug
If you disable "Last Recorded" entity ( ex: if you don't need that data) the integration still tries to get that information from the cameras resulting in errors in the log. Additionally, the snapshots are also taken upon integration startup. 

This seems to be the regression of issue #59 that's been already fixed 

To Reproduce
Disable the "sensor.xxxxxx_last_record" entity in HA. Reload this integration

Expected behavior
You should not get any errors in the log and snapshots should not be created.

Debug log would be very helpful:
```
Traceback (most recent call last):
File "/config/custom_components/reolink_cctv/sensor.py", line 258, in _update_last_record
self.async_schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 690, in async_schedule_update_ha_state
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Garage last record>
2022-12-10 16:34:24.479 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved

Traceback (most recent call last):
File "/config/custom_components/reolink_cctv/sensor.py", line 258, in _update_last_record
self.async_schedule_update_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 690, in async_schedule_update_ha_state
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_write_ha_state
raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Kitchen last record>
2022-12-10 16:34:24.483 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
```

**Comment by JimStar** [comment]
What HA version you have?

**Comment by skynet01** [comment]
I am on the latest one: 2022.12.1

**Comment by skynet01** [comment]
Yeah it happened on 0.39 and I believe with HA 2022.11 as well.

**Comment by JimStar** [comment]
No way it could happen if the sensor was disabled, the code of this method clearly exits if HA returns `False` from its `enabled` property:

![1](https://user-images.githubusercontent.com/3421219/206926896-4a8d531d-a0ec-4817-b5f8-aaf5683c214e.png)

The only thing I could think of right now - is if HA somehow returns "enabled" to this sensor during startup...

**Comment by skynet01** [comment]
Maybe wait a little for HA to finish startup ex 30 seconds before checking for status of those sensors?

**Comment by JimStar** [comment]
I hope is should be fixed by [0.1.4](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.4).

**Comment by skynet01** [comment]
Sowwy still an issue after the 0.1.4 update. Maybe your function returns _unavailable_ so it continues?

**Comment by JimStar** [comment]
Please attach a full debug log file, after this component's debugging enabled in HA config as shown in the issue template...

**Comment by skynet01** [comment]
Here you go: https://gist.github.com/skynet01/32ffc99f7b8dfdf4feb3239326981c08

**Comment by JimStar** [comment]
Try the [0.1.5](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.5). I test few more things in there...

**Comment by JimStar** [comment]
F@#&. :exploding_head:

OK, I'll investigate this further...

**Comment by JimStar** [comment]
Should be fixed in [0.1.12](https://github.com/JimStar/reolink_cctv/releases/tag/0.1.12).

**Comment by skynet01** [comment]
Confirming that the 0.1.12 fixed the issue. Thank you!!! 🥰
