### ISSUE TITLE
Integration still tries to get "last recorded" information even if Last_Record sensor entity is disabled.

### ISSUE THREAD

**Issue by skynet01** [JimStar/reolink_cctv#59]
**Describe the bug**
If you disable "Last Recorded" entity ( ex: if you don't need that data) the integration still tries to get that information from the cameras resulting in errors in the log. Additionally, the snapshots are also taken upon integration startup.  

**To Reproduce**
Disable the "sensor.xxxxxx_last_record" entity in HA. Reload this integration

**Expected behavior**
You should not get any errors in the log and snapshots should not be created. 

**Debug log would be very helpful**

```
Logger: homeassistant
Source: helpers/entity.py:538
First occurred: 10:23:25 AM (6 occurrences)
Last logged: 12:32:45 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_cctv/sensor.py", line 255, in _update_last_record
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 690, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Garage last record>
```

**Comment by JimStar** [comment]
Yep, that's a bug, thanks!  
Will fix it in the next version...

**Comment by JimStar** [comment]
Fixed in [0.0.28](https://github.com/JimStar/reolink_cctv/releases/tag/0.0.28).

**Comment by skynet01** [comment]
Looks like I am still getting this issue with the doorbell camera. Not sure if it's regression or the original. @JimStar 

```
Logger: homeassistant
Source: helpers/entity.py:538
First occurred: 1:48:22 PM (7 occurrences)
Last logged: 1:48:22 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/reolink_cctv/sensor.py", line 258, in _update_last_record
    self.async_schedule_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 690, in async_schedule_update_ha_state
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in async_write_ha_state
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <Entity Doorbell last record>
```
